default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
<<<<<<< HEAD
  <<: *default
  username: sqlite3
  database: db-dev

test:
  <<: *default
  username: sqlite3
  database: db-test
=======
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
>>>>>>> eventnxt/master

production:
  url: <%= ENV['DATABASE_URL'] %>
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   adapter: sqlite3
#   database: db/development.sqlite3

# test:
#   <<: *default
#   adapter: sqlite3
#   database: db/test.sqlite3
